{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zly.aab",
    "module": "myGradlePlugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myGradlePlugin-1.0.1.jar",
          "url": "myGradlePlugin-1.0.1.jar",
          "size": 9559,
          "sha512": "e1f06658393b4f3101301c10b302d430ef9d113d411f452b8dc782d962539602321b4347017783953cb347676ff3859f39ab00f1bc6851494a4502e6b8a88a81",
          "sha256": "8aab3b54d362d9a6acc04d2b4703a7871acff4437cedc6aaeba2577a9618e23d",
          "sha1": "3f3a976396265206e2d9a5e9a107a33ce21eab4e",
          "md5": "b504f55549179276712e32ea8f25b56d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "myGradlePlugin-1.0.1.jar",
          "url": "myGradlePlugin-1.0.1.jar",
          "size": 9559,
          "sha512": "e1f06658393b4f3101301c10b302d430ef9d113d411f452b8dc782d962539602321b4347017783953cb347676ff3859f39ab00f1bc6851494a4502e6b8a88a81",
          "sha256": "8aab3b54d362d9a6acc04d2b4703a7871acff4437cedc6aaeba2577a9618e23d",
          "sha1": "3f3a976396265206e2d9a5e9a107a33ce21eab4e",
          "md5": "b504f55549179276712e32ea8f25b56d"
        }
      ]
    }
  ]
}
