{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zly.aab",
    "module": "myGradlePlugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myGradlePlugin-1.0.1.jar",
          "url": "myGradlePlugin-1.0.1.jar",
          "size": 9359,
          "sha512": "aaec6ef709c6aebf2398dfbf4ba497e02f4a6cdd8c66e46f1a8c97e8c4b0c182897218d8372fc963ab6c977c91db7123a1be324ccf2f62451f9ff7f2a7546e1e",
          "sha256": "2641c27483aae72a816b71cadadacea33663b21f26fbb97d471135b27fc4312b",
          "sha1": "6646497ec98c9e326ed0487336740e3db773acab",
          "md5": "6562822e9868fbacf72f6e46fead76b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "16.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "myGradlePlugin-1.0.1.jar",
          "url": "myGradlePlugin-1.0.1.jar",
          "size": 9359,
          "sha512": "aaec6ef709c6aebf2398dfbf4ba497e02f4a6cdd8c66e46f1a8c97e8c4b0c182897218d8372fc963ab6c977c91db7123a1be324ccf2f62451f9ff7f2a7546e1e",
          "sha256": "2641c27483aae72a816b71cadadacea33663b21f26fbb97d471135b27fc4312b",
          "sha1": "6646497ec98c9e326ed0487336740e3db773acab",
          "md5": "6562822e9868fbacf72f6e46fead76b3"
        }
      ]
    }
  ]
}
