{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zly.aab",
    "module": "myGradlePlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myGradlePlugin-1.0.0.jar",
          "url": "myGradlePlugin-1.0.0.jar",
          "size": 9174,
          "sha512": "2e591ddf69c6bd59686fcda1fb993aa3b3666667a882129b624d14c43bea45de218c42dc1fce45fcac092e9314dc9e7bfa052898aa0cedce90d985ed9a683b53",
          "sha256": "772c2f6ada9741c13f91fa89cd6727f2f6a65e8f829223af1300c69d37e2c641",
          "sha1": "bc3059ec1b7251d6b7931b834b53afb7e7ee1e65",
          "md5": "cc6c8a2f185cd1aa3e9ee0822c7781db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "15.0"
          }
        }
      ],
      "files": [
        {
          "name": "myGradlePlugin-1.0.0.jar",
          "url": "myGradlePlugin-1.0.0.jar",
          "size": 9174,
          "sha512": "2e591ddf69c6bd59686fcda1fb993aa3b3666667a882129b624d14c43bea45de218c42dc1fce45fcac092e9314dc9e7bfa052898aa0cedce90d985ed9a683b53",
          "sha256": "772c2f6ada9741c13f91fa89cd6727f2f6a65e8f829223af1300c69d37e2c641",
          "sha1": "bc3059ec1b7251d6b7931b834b53afb7e7ee1e65",
          "md5": "cc6c8a2f185cd1aa3e9ee0822c7781db"
        }
      ]
    }
  ]
}
